site_name: {{ cookiecutter.site_name }}

theme: rtd-dropdown
use_directory_urls: false
strict: true
markdown_extensions:
  - extra
  - lightbox
  - math:
      enable_dollar_delimiter: True
extra_css:
  - css/custom.css
  - css/lightbox.min.css
extra_javascript:
  - js/lightbox.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_HTML

